name: action_test

on: [push]

jobs:
  github-actions-test:
    runs-on: ubuntu-latest
    
    steps: 
      - name: List Files
        run: |
          pwd
          ls
      - name: checkout
        uses: actions/checkout@v2
      - name: List Files after checkout
        run: |
          pwd
          ls        
