name: container

on: push

jobs:

  first:
    runs-on: ubuntu-latest
    container:
      image: node:16-alpine3.11
    steps:
      - name: log node version
        run: |
          node -v
          cat /etc/os-release

  second:
    runs-on: ubuntu-latest
    steps:
      - name: os-version
        run: |
          node -v
          cat /etc/os-release      