name: context
on: [push]

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: "step1"
        run: |
          echo "$STEP_ENV"  
          echo "$STEP_ENV.event.after"  
        env:
          STEP_ENV:  ${{ toJson(github) }}     
  functions:
    runs-on: ubuntu-latest
    steps:
      - name: dump
        run : |
          echo "${{ format('Hello {0}{1}{2}','World','!','!') }}" 
          echo "${{ startsWith('abc','ab') }}"      
          echo "${{ toJson(strategy) }}" 
          echo "${{ toJson(matrix) }}" 
          echo "${{ github.event.after }}"
          echo "${{ github.context }}" 
