name: context
on: [push]

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: "step1"
        run: |
          echo "$STEP_ENV"  
          echo "$STEP_ENV.event.after"  
        env:
          STEP_ENV:  ${{ toJson(github) }}     
  functions:
    strategy:
      matrix:
        node: [6,8,10]
        os: [ubuntu-latest.macos-latest,windows-latest]
    #fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
      - name: dump
        run : |
          echo "${{ format('Hello {0}{1}{2}','World','!','!') }}" 
          echo "${{ startsWith('abc','ab') }}"      
          echo "${{ toJson(strategy) }}" 
          echo "${{ toJson(matrix) }}" 
          echo "${{ github.event }}"
          echo "${{ github.context }}" 
