name: context
on: [push]

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: "step1"
        run: |
          echo "$STEP_ENV"  
          echo "$STEP_ENV.event.after"  
        env:
          STEP_ENV:  ${{ toJson(github) }}     
  functions:
    runs-on: ubuntu-latest
    steps:
      - name: dump
        run : |
          echo "${{ format('Hello {}{}{}','World','!','!') }}"        